import java.time.Duration;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Login_successfully {
    public static void main(String[] args) {
//    	
//    	ExtentReports extent = new ExtentReports();
//        ExtentSparkReporter spark = new ExtentSparkReporter(
//        		"target/FreightSmith/ExtentReportsForScheduleProSchedulePO_07_02_2024.html");
//        extent.attachReporter(spark);
    	
    	// username : rahul 
    	// password : rahulshettyacademy
    	WebDriver driver = new ChromeDriver();
    	
     // First let's fill up the username section
    	
	    String TEST_URL = "https://rahulshettyacademy.com/locatorspractice/";
	    String _PASSWORD_ = "rahulshettyacademy";
	   
	    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(6));
	   
	    // Step 1 : Visiting the url 
	    
	    driver.get(TEST_URL);
    	
	    // Step 2 : Filliing up the input fields
	   
//    	driver.findElement(By.cssSelector("#inputUsername")).sendKeys("rahul");
	    
	    // Using Xpath
	    driver.findElement(By.xpath("//")).sendKeys("rahul");
        
    	driver.findElement(By.xpath("//input[@type='password']")).sendKeys(_PASSWORD_); // Xpath important
    	
    	// What if we want to use regular expression to target this input field
    	
//    	driver.findElement(By.xpath("//input[@type*='pass']")).sendKeys(_PASSWORD_);
    	
    	
    	// Step 3 : Checking on the checkboxes
    
    	driver.findElement(By.id("chkboxOne")).click();
    	driver.findElement(By.id("chkboxTwo")).click();
    
    	// Step 4 : Clicking the sign in button.
    	driver.findElement(By.cssSelector(".signInBtn")).click();
    	
    	// Step 5 : Now let's log out from this page.
    	try {
    	    Thread.sleep(4000); // Sleep for 4000 milliseconds (4 seconds)
        	driver.findElement(By.className("logout-btn")).click();
    	} catch (InterruptedException e) {
    	    // Handle the interrupted exception
    	    e.printStackTrace();
    	}
    	
    	// Extent Report gets generated by selenium.
    	

    }
}
